### ISSUE TITLE
possible problem?

### ISSUE THREAD

**Issue by ghost** [boxidau/rax-autoscaler#22]
Hey Simon/Simone.  Not sure what's happening, but i seem to be getting issue updates from this repo all of a sudden (since 9:40am).  Emails are addressed to rax-autoscaler@noreply.github.com but they're coming to my profile (eitsglobal).  I've dropped a support/bug report to github as I have no knowledge of signing up for this repo.  lots of loves to you Simon, but do you want me all up in your repo?

**Comment by ghost** [comment]
Uh Simon, not cool mate. It appears you created this repo on my account.  you shouldn't be logging in with eitsglobal.  my bad for not changing the passwords but then i didn't think i'd need to with you.  Is this what's happened or do i need to be worried about github security in general (which is even less cool)?

**Comment by siso** [comment]
Hi @eitsglobal, I'll have a chat with Simon shortly. Regards -- Simone

**Comment by boxidau** [comment]
Hey Steve @eitsglobal, this was definitely created on my own personal account boxidau, I don't have access to eitsglobal at all. Not sure why you would be getting notifications, I'll look into it.

**Comment by boxidau** [comment]
So my old simonm@eits... email was still associated to my github account it was probably just getting notifications and the email catchall was forwarding to you? I've removed that email from my profile, hopefully that should solve it.

**Comment by boxidau** [comment]
I've scoured my github profile and as far as I can tell now that I've removed that old email on my account, I no longer have any references to eits. Also there is definitely no need to worry about security with me and to be frank I don't appreciate the implication that I would do anything untoward.

I'll close this issue now, let me know if you are still receiving notifications.
Cheers,
Simon

**Comment by ghost** [comment]
Hi Simon,
Thanks for following up on this. I’m not sure what the story is.  When i looked at our account on github, there was a rax-autoscalar repo on our public tab.  I tried assigning the repo to your boxidau profile but couldn’t because you had a fork on your account.  I’ve deleted the repo, knowing forks of public repos don’t get deleted.  But I’m still getting updates on issues for some reason. issues #23, #20, #24, #8 were posted to this morning.

On 11 Nov 2014, at 1:07 pm, Simon Mirco <notifications@github.com<mailto:notifications@github.com>> wrote:

So my old simonm@eitsglobal.commailto:simonm@eitsglobal.com email was still associated to my github account it was probably just getting notifications and the email catchall was forwarding to you? I've removed that email from my profile, hopefully that should solve it.

**Comment by ghost** [comment]
Uh just saw this.  OK thanks for your frankness Simon, though i’d hope you understand, finding your repo posted on my account with me as the owner is quite troubling.  I’ve asked github to investigate how this has come about.

On 11 Nov 2014, at 1:19 pm, Simon Mirco <notifications@github.com<mailto:notifications@github.com>> wrote:

I've scoured my github profile and as far as I can tell now that I've removed that old email on my account, I no longer have any references to eits. Also there is definitely no need to worry about security with me and to be frank I don't appreciate the implication that I would do anything untoward.

I'll close this issue now, let me know if you are still receiving notifications.
Cheers,
Simon
